import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import {ToastContainer} from "react-toastify";
import {LoginProvider} from "@/app/providers/LoginProvider";
import ModalLogin from "@/app/components/ModalLogin";
import Sidebar from "@/app/components/Sidebar";
import {ListingProvider} from "@/app/providers/ListingProvider";
import ModalListing from "@/app/components/ModalListing";
import AppShell from "@/app/components/AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kitchen Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>

    </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <LoginProvider>
        <ListingProvider>
          <AppShell>{children}</AppShell>
          <ToastContainer position="bottom-center" autoClose={2500} />
        </ListingProvider>
      </LoginProvider>
      </body>
    </html>
  );
}
